datafile: ../../../data/data_GASIF_biomass.csv
labels:
  - volCO (%)
  - volH2 (%)
  - volCOMB (%)
  - GAS (m3/kg biom)
features:
  - SA
  - SBR
  - HHVbiom (MJ/kg)
  - T (K)
  - SR
  - C (%)
  - H (%)
  - O (%)
  - ash (%)
  - VM (%)
  - FC (%)
  - MC (%)
kernel: rbf_linear
coregionalized: true
ard: true
y_scramble: false
tags:
