# @package _global_

# specify here default training configuration
defaults:
  - _self_
  - trainer: default.yaml
  - model: default.yaml
  - data: core.yaml

seed: 1234

project_name: biomassml
entity: kjappelbaum
log_model: false

swa: false
tags: 
patience: 10

