_target_: src.biomassml.models.fcnn.FCNN

dropout_p:  0.3
initialization:  kaiming
activation: ReLU
batch_norm:  true
dropconnect: true
chemistry_backbone_layers: 48-48-48
process_backbone_layers: 48-48-48
head_layers: null
pretrained_chemistry_backbone: null 
pretrained_process_backbone: null 
chemistry_bb_output_dim: null
process_bb_output_dim: null