_target_: src.biomassml.models.fcnn.FCNN

dropout_p:  0.1
initialization:  kaiming
activation: ReLU
batch_norm:  false
dropconnect: false
chemistry_backbone_layers: 8-16
process_backbone_layers: 6-16
head_layers: 16-16-16
pretrained_chemistry_backbone: null 
pretrained_process_backbone: null 
chemistry_bb_output_dim: null
process_bb_output_dim: null