_target_: pytorch_lightning.Trainer

gpus: null

min_epochs: 1
max_epochs: 200

resume_from_checkpoint: null

precision: 32

auto_lr_find: false 

overfit_batches: 0.0

limit_train_batches: 1.0

num_sanity_val_steps: 0